# -*- coding: utf-8 -*-

# BURAYA İSTEDİĞİN KADAR KİTAP EKLEYEBİLİRSİN (Hedef: 500+)
BOOKS = [
    {"book": "İnsanın Anlam Arayışı", "book_author": "Viktor E. Frankl"},
    {"book": "İyi Hissetmek", "book_author": "Dr. David Burns"},
    {"book": "Sevme Sanatı", "book_author": "Erich Fromm"},
    {"book": "Bilinçaltı", "book_author": "Sigmund Freud"},
    {"book": "Akış: Mutluluk Bilimi", "book_author": "Mihaly Csikszentmihalyi"},
    {"book": "Düşünmek, Hızlı ve Yavaş", "book_author": "Daniel Kahneman"},
    {"book": "Alışkanlıkların Gücü", "book_author": "Charles Duhigg"},
    {"book": "Seninle Başlamadı", "book_author": "Mark Wolynn"},
    {"book": "Kendime Düşünceler", "book_author": "Marcus Aurelius"},
    {"book": "Köpek Gibi Büyütülmüş Çocuk", "book_author": "Bruce D. Perry"},
    {"book": "Varoluşçu Psikoterapi", "book_author": "Irvin D. Yalom"},
    {"book": "Beden Kayıt Tutar", "book_author": "Bessel van der Kolk"},
    {"book": "Gen: Kısa Bir Tarih", "book_author": "Siddhartha Mukherjee"},
    {"book": "Gen Bencildir", "book_author": "Richard Dawkins"},
    {"book": "İkili Sarmal", "book_author": "James D. Watson"},
    {"book": "Yaşam Nedir?", "book_author": "Erwin Schrödinger"},
    {"book": "Davranış", "book_author": "Robert M. Sapolsky"},
    {"book": "Karısını Şapka Sanan Adam", "book_author": "Oliver Sacks"},
    {"book": "İnsan Olmak", "book_author": "Engin Geçtan"},
    {"book": "Hayatın Kökleri", "book_author": "Mahlon B. Hoagland"},
    {"book": "İçimizdeki Balık", "book_author": "Neil Shubin"},
    {"book": "Türlerin Kökeni", "book_author": "Charles Darwin"},
    {"book": "Kozmos", "book_author": "Carl Sagan"},
    {"book": "Zamanın Kısa Tarihi", "book_author": "Stephen Hawking"},
    {"book": "Incognito: Beynin Gizli Hayatı", "book_author": "David Eagleman"},
    {"book": "Beyin: Senin Hikayen", "book_author": "David Eagleman"},
    {"book": "Kör Saatçi", "book_author": "Richard Dawkins"},
    {"book": "Tüfek, Mikrop ve Çelik", "book_author": "Jared Diamond"},
    {"book": "Hayvanlardan Tanrılara Sapiens", "book_author": "Yuval Noah Harari"},
    {"book": "Homo Deus", "book_author": "Yuval Noah Harari"},
    {"book": "Bağlanma", "book_author": "Amir Levine, Rachel Heller"},
    {"book": "Şiddetsiz İletişim", "book_author": "Marshall B. Rosenberg"},
    {"book": "Nietzsche Ağladığında", "book_author": "Irvin D. Yalom"},
    {"book": "Bir Psikiyatristin Gizli Defteri", "book_author": "Gary Small"},
    {"book": "Duygusal Zeka", "book_author": "Daniel Goleman"},
    {"book": "Kötülüğün Anatomisi", "book_author": "Michael H. Stone"},
    {"book": "Zamanın Doğası", "book_author": "Carlo Rovelli"},
    {"book": "Olağanüstü Yanılgılar", "book_author": "Charles Mackay"},
    {"book": "Aşkın Celladı", "book_author": "Irvin D. Yalom"},
    {"book": "Körlük", "book_author": "José Saramago"},
    {"book": "Cesur Yeni Dünya", "book_author": "Aldous Huxley"},
    {"book": "1984", "book_author": "George Orwell"},
    {"book": "Hayvan Çiftliği", "book_author": "George Orwell"},
    {"book": "Simyacı", "book_author": "Paulo Coelho"},
    {"book": "Böyle Buyurdu Zerdüşt", "book_author": "Friedrich Nietzsche"},
    {"book": "Suç ve Ceza", "book_author": "Fyodor Dostoyevski"},
    {"book": "İçimizdeki Şeytan", "book_author": "Sabahattin Ali"},
    {"book": "Yabancı", "book_author": "Albert Camus"}
]

# BURAYA İSTEDİĞİN KADAR ŞARKI EKLEYEBİLİRSİN (Hedef: 500+)
SONGS = [
    {"song": "Nuvole Bianche - Ludovico Einaudi", "song_desc": "Zihni temizleyen derin bir sükûnet hissi."},
    {"song": "Clair de Lune - Claude Debussy", "song_desc": "Gece dinginliği ve içsel huzur."},
    {"song": "Experience - Ludovico Einaudi", "song_desc": "Hayatın ritmine uyum sağlayan güçlü bir melodi."},
    {"song": "Gymnopédie No.1 - Erik Satie", "song_desc": "Yavaş, melankolik ve dinlendirici bir atmosfer."},
    {"song": "Spiegel im Spiegel - Arvo Pärt", "song_desc": "Zamanın durduğunu hissettiren minimalist bir şaheser."},
    {"song": "Weightless - Marconi Union", "song_desc": "Bilimsel olarak stresi azalttığı kanıtlanmış frekanslar."},
    {"song": "River Flows in You - Yiruma", "song_desc": "Duygusal farkındalığı artıran piyano tınıları."},
    {"song": "A Model of the Universe - Jóhann Jóhannsson", "song_desc": "Evrenin ve zihnin sonsuzluğunu hissettiren tınılar."},
    {"song": "Any Other Name - Thomas Newman", "song_desc": "Kendi içine dönüş ve sessiz bir kabulleniş."},
    {"song": "Nocturne op.9 No.2 - Chopin", "song_desc": "Klasik müziğin en rahatlatıcı ve zarif dokunuşlarından biri."},
    {"song": "On the Nature of Daylight - Max Richter", "song_desc": "Hücrelere kadar işleyen derin ve dramatik bir yaylı kompozisyonu."},
    {"song": "Comptine d'un autre été - Yann Tiersen", "song_desc": "Zihni harekete geçiren ritmik ve umut dolu bir melodi."},
    {"song": "Time - Hans Zimmer", "song_desc": "Zaman algısını büken, yavaşça yükselen sinematik bir deneyim."},
    {"song": "Cornfield Chase - Hans Zimmer", "song_desc": "Merak duygusunu ve keşfetme arzusunu tetikleyen notalar."},
    {"song": "Avril 14th - Aphex Twin", "song_desc": "Sıcak, analog ve nostaljik bir piyano eseri."},
    {"song": "Valse, Op. 64 No. 2 - Chopin", "song_desc": "Zarafet ve hüznün kusursuz bir vals formunda buluşması."},
    {"song": "Written on the Sky - Max Richter", "song_desc": "Gökyüzüne bakarken zihni yavaşlatan kısa ama etkili bir parça."},
    {"song": "Metamorphosis One - Philip Glass", "song_desc": "Döngüsel notalarla zihinsel odaklanmayı artıran bir şaheser."},
    {"song": "The Arts and the Hours - Jean-Philippe Rameau", "song_desc": "Geçmişin bilgeliğini taşıyan zarif bir klasik dönem eseri."},
    {"song": "Opening - Philip Glass", "song_desc": "Güne başlarken veya yeni bir fikir üretirken dinlenecek ritmik akış."},
    {"song": "Day One - Hans Zimmer", "song_desc": "Yeni bir başlangıcın ve sonsuz uzayın sesli tasviri."},
    {"song": "To Build a Home - The Cinematic Orchestra", "song_desc": "Aidiyet ve huzur duygusunu alevlendiren epik eser."},
    {"song": "Arrival of the Birds - The Cinematic Orchestra", "song_desc": "Doğanın muazzam uyanışını yansıtan büyüleyici notalar."},
    {"song": "Requiem, K. 626: Lacrimosa - W.A. Mozart", "song_desc": "Tarihin en sarsıcı ve duygusal klasik müzik eserlerinden biri."},
    {"song": "The Blue Notebooks - Max Richter", "song_desc": "Edebiyat ve notaların karanlık ama huzur veren buluşması."},
    {"song": "Una Mattina - Ludovico Einaudi", "song_desc": "Güneşin doğuşunu hissettiren yumuşak bir melodi."},
    {"song": "Moonlight Sonata - Beethoven", "song_desc": "Tutku, hüzün ve kusursuzluğun müzikal dışavurumu."},
    {"song": "Cello Suite No. 1 - J.S. Bach", "song_desc": "Matematiksel bir kusursuzluğa sahip çello zarafeti."},
    {"song": "Air on the G String - J.S. Bach", "song_desc": "Rahatlatıcı, akıcı ve zamanın ötesinde bir başyapıt."},
    {"song": "Passacaglia - Handel / Halvorsen", "song_desc": "Dinamik, güçlü ve entelektüel bir yaylı düet."}
]